package com.github.narms.mathparser;

public enum SyntaxType {
    KEYVARTOKEN, NUMTOKEN, OPTOKEN, LPARTOKEN, RPARTOKEN, SYMTOKEN, BINOPEXPR, CONSTEXPR, PARENCONTAINER, VAREXPR, UNARYOPEXPR, BOOLEXPR;
}
